# information about COM port
[port]
name = "/dev/ttyUSB0"                                         # Port name/path
frequency = 9600                                              # Port frequency

# information about request file
[request_file]
path = "/home/andofwinds/Desktop/comrq/request_sequence.rsq"  # Path to Sequence file
delay = 60                                                    # delay between requests

